/*
 * NIST FIPS 202 known-answer tests for Keccak (SHA3-256 / SHAKE-128 / SHAKE-256).
 *
 * Golden values were generated by CPython's `_sha3` (FIPS-202-conformant) and
 * cross-checked against the canonical NIST vectors:
 *   - SHA3-256("")  = a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a
 *   - SHAKE256("abc", 64) = 483366601360a877... (FIPS 202 Appendix B3)
 * Vectors cover: domain-sep 0x06 vs 0x1F, rates 136/168, pad10* on the empty
 * message, single- and multi-block squeeze.
 */
package ch.trancee.kemseed

import kotlin.test.Test
import kotlin.test.assertContentEquals

internal class KeccakTest {

    private fun h(s: String): ByteArray {
        val out = ByteArray(s.length / 2)
        for (i in out.indices) {
            out[i] = s.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
        return out
    }

    @Test
    fun sha3_256_emptyMatchesNist() {
        assertContentEquals(
            h("a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a"),
            Keccak.sha3_256(ByteArray(0)),
        )
    }

    @Test
    fun sha3_256_abcMatchesNist() {
        assertContentEquals(
            h("3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532"),
            Keccak.sha3_256("abc".encodeToByteArray()),
        )
    }

    @Test
    fun sha3_256_abcdefMatchesNist() {
        assertContentEquals(
            h("59890c1d183aa279505750422e6384ccb1499c793872d6f31bb3bcaa4bc9f5a5"),
            Keccak.sha3_256("abcdef".encodeToByteArray()),
        )
    }

    // ---- SHA3-512 (FIPS 202 §6.1): the G hash FIPS 203 ML-KEM uses in KeyGen
    //      (rho||sigma_hat = G(d)), so it is a prerequisite for Phase 0b.
    //      rate=72 B, capacity=512 bit, domain sep 0x06, output 64 B.
    @Test
    fun sha3_512_emptyMatchesNist() {
        assertContentEquals(
            h("a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26"),
            Keccak.sha3_512(ByteArray(0)),
        )
    }

    @Test
    fun sha3_512_abcMatchesNist() {
        assertContentEquals(
            h("b751850b1a57168a5693cd924b6b096e08f621827444f70d884f5d0240d2712e10e116e9192af3c91a7ec57647e3934057340b4cf408d5a56592f8274eec53f0"),
            Keccak.sha3_512("abc".encodeToByteArray()),
        )
    }

    @Test
    fun sha3_512_abcdefMatchesNist() {
        assertContentEquals(
            h("01309a45c57cd7faef9ee6bb95fed29e5e2e0312af12a95fffeee340e5e5948b4652d26ae4b75976a53cc1612141af6e24df36517a61f46a1a05f59cf667046a"),
            Keccak.sha3_512("abcdef".encodeToByteArray()),
        )
    }

    @Test
    fun sha3_512_abc30_multiblockMatchesNist() { // 90 B > rate 72 -> 2 absorb blocks
        assertContentEquals(
            h("844f9aec1be09d1050680f91b8c3ad1fd307fa5aa4a5afcf8db14fb82f9c30b341e761160f3ac4b0d6d8a9b82d7086832ba5cc240e996e94f2020512ef9717ee"),
            Keccak.sha3_512("abc".repeat(30).encodeToByteArray()),
        )
    }

    @Test
    fun shake256_emptyMatchesNist() {
        assertContentEquals(
            h("46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f" +
                "d75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be"),
            Keccak.shake256(ByteArray(0), 64),
        )
    }

    @Test
    fun shake256_abc_matchesNist() {
        assertContentEquals(
            h("483366601360a8771c6863080cc4114d8db44530f8f1e1ee4f94ea37e78b5739" +
                "d5a15bef186a5386c75744c0527e1faa9f8726e462a12a4feb06bd8801e751e4"),
            Keccak.shake256("abc".encodeToByteArray(), 64),
        )
    }

    @Test
    fun shake256_abc_200_multiblockMatchesNist() { // 200 B > rate 136 -> 2 squeeze blocks
        assertContentEquals(
            h("483366601360a8771c6863080cc4114d8db44530f8f1e1ee4f94ea37e78b5739" +
                "d5a15bef186a5386c75744c0527e1faa9f8726e462a12a4feb06bd8801e751e4" +
                "1385141204f329979fd3047a13c5657724ada64d2470157b3cdc288620944d78d" +
                "bcddbd912993f0913f164fb2ce95131a2d09a3e6d51cbfc622720d7a75c6334e8" +
                "a2d7ec71a7cc29cf0ea610eeff1a588290a53000faa79932becec0bd3cd0b33a7" +
                "e5d397fed1ada9442b99903f4dcfd8559ed3950faf40fe6f3b5d710ed3b677513" +
                "771af6bfe119"),
            Keccak.shake256("abc".encodeToByteArray(), 200),
        )
    }

    @Test
    fun shake128_emptyMatchesNist() {
        assertContentEquals(
            h("7f9c2ba4e88f827d616045507605853ed73b8093f6efbc88eb1a6eacfa66ef26"),
            Keccak.shake128(ByteArray(0), 32),
        )
    }

    @Test
    fun shake128_abcMatchesNist() {
        assertContentEquals(
            h("5881092dd818bf5cf8a3ddb793fbcba74097d5c526a6d35f97b83351940f2cc8"),
            Keccak.shake128("abc".encodeToByteArray(), 32),
        )
    }

    @Test
    fun shake128_abc_400_multiblockMatchesNist() { // 400 B > rate 168 -> 3 squeeze blocks
        assertContentEquals(
            h("5881092dd818bf5cf8a3ddb793fbcba74097d5c526a6d35f97b83351940f2cc8" +
                "44c50af32acd3f2cdd066568706f509bc1bdde58295dae3f891a9a0fca5783789" +
                "a41f8611214ce612394df286a62d1a2252aa94db9c538956c717dc2bed4f232a" +
                "0294c857c730aa16067ac1062f1201fb0d377cfb9cde4c63599b27f3462bba4a" +
                "0ed296c801f9ff7f57302bb3076ee145f97a32ae68e76ab66c48d51675bd49ac" +
                "c29082f5647584e6aa01b3f5af057805f973ff8ecb8b226ac32ada6f01c1fcd4" +
                "818cb006aa5b4cdb3611eb1e533c8964cacfdf31012cd3fb744d02225b988b475" +
                "375faad996eb1b9176ecb0f8b2871723d6dbb804e23357e50732f5cfc904b1319" +
                "795000d7361d9e5e1b77b4b8f5774aa1482cfa58f83096bdb2e06a3eed543a389" +
                "19b57ecbec737f4086be007f8ef80094ceea8807193d46e9be540b6e99b4c1c71" +
                "507095028a024e8d39aa8f4c5854cedd50d30a223e7d54e9a24f0a2526b31002a" +
                "fbd1b4ebea69c8400c3deb4c1c35d6dbb75651b284076f5fde47b4a0586ee173e" +
                "30bd4d08f2bc59c6114bdd745"),
            Keccak.shake128("abc".encodeToByteArray(), 400),
        )
    }
}
