@file:OptIn(KompactPreview::class)

package ch.trancee.kemseed.pdu

import ch.trancee.kompact.annotations.KompactField
import ch.trancee.kompact.annotations.KompactModel
import ch.trancee.kompact.annotations.KompactPreview
import ch.trancee.kompact.runtime.KompactWriter
import ch.trancee.kompact.runtime.ScalarType

/**
 * AD-PDU plaintext header (8-bit, LSB-first): a `@KompactModel` `expect value class`
 * over a 1-byte `ByteArray`. Platform `actual`s are GENERATED by the project's KSP
 * processor from this `expect` + the `@KompactField`-annotated accessors below.
 *
 * Read/write accessors use `readBits`/`writeBits` (zero-alloc, LSB-first); the companion
 * `create(...)` delegates to the shared `[encodeAdPduHeader]`. API-stable: `.raw`,
 * `.version`, `.pduType`, `.reserved`, `[encodeAdPduHeader]` are unchanged vs. the prior
 * hand-written actuals. Re-enabling `@KommutModel` here swaps hand-written actuals for
 * generated ones: the 0.1.5 generator fix resolved defect #3 (non-`val` ctor `raw` param,
 * rejected for `@JvmInline value class`) that previously blocked codegen (ADR-0003 §v1.4).
 *
 * Layout (`#08` §3 Phase D; ADR-0003 §v1.2), unsigned:
 *   [0..3]  version   (4 bits)  = AD_PDU_VERSION (1)
 *   [4..6]  pduType   (3 bits)  0=data,1=ack,2=control,3=nack; 4..7 reserved
 *   [7..7]  reserved  (1 bit)   must be 0
 *
 * Direction + 8-byte monotonic seqno are NOT carried here — per `#08` §1.6 they bind the
 * GCM IV via `Hmb1Handshake.iv(dir, nonce) = 0x11 | dir(1) | nonce(8) | 0x0000`.
 * `[raw]` >= 1 byte; raw == `[0x21]` for `v=1, p=2, r=0`.
 */

public const val AD_PDU_VERSION: Int = 1

/** Bit-width of the packed AD-PDU header (4 + 3 + 1 = 8 bits => 1 byte). */
public const val AD_PDU_HEADER_BITS: Int = 8

/**
 * AD-PDU payload type (the 3-bit `pduType` field of [AdPduHeader]).
 *
 * 3 bits => 8 wire values (0..7). Canonical set occupies 0..3; 4..7 reserved for future
 * allocation by the mesh (Phase-1b design choice — `#08` §1.6 frees the GCM IV and
 * direction, not the data-PDU payload fields). Kept as a typed enum at the API layer
 * carrying the 3-bit wire ordinal: the KSP processor packs `pduType` as a plain unsigned
 * Int scalar, so the enum membership check lives here (post-auth decode), not in the bit
 * packer — the `enumWidth` codegen path is not exercised by this layout.
 */
public enum class PduType(public val wire: Int) {
    DATA(0),
    ACK(1),
    CONTROL(2),
    NACK(3),
    ;

    public companion object {
        /** Decode a 3-bit wire ordinal (0..7) to the canonical `PduType`. Throws on reserved 4..7. */
        public fun fromWire(wire: Int): PduType = entries.firstOrNull { it.wire == wire }
            ?: throw IllegalArgumentException("unknown AD-PDU pduType wire=$wire (reserved 4..7)")
    }
}

@KompactModel
public expect value class AdPduHeader(
    public val raw: ByteArray,
) {
    public companion object {
        public fun create(version: Int, pduType: Int, reserved: Int): AdPduHeader
    }

    @KompactField(bitOffset = 0, bitWidth = 4) public var version: Int

    @KompactField(bitOffset = 4, bitWidth = 3) public var pduType: Int

    @KompactField(bitOffset = 7, bitWidth = 1) public var reserved: Int
}

/** Shared encode helper for [AdPduHeader] (write path). Also callable directly to
 * build an [AdPduHeader] from field values. Pure commonMain — `KompactWriter`
 * only; no `java.*`, no `clone()`. Layout: version(4) | pduType(3) | reserved(1),
 * LSB-first — bit-exact against the goldens in [AdPduTest].
 */
internal fun encodeAdPduHeader(version: Int, pduType: Int, reserved: Int): ByteArray {
    val w = KompactWriter()
    w.writeScalar(ScalarType.of(4, signed = false), version.toLong())
    w.writeScalar(ScalarType.of(3, signed = false), pduType.toLong())
    w.writeScalar(ScalarType.of(1, signed = false), reserved.toLong())
    return w.build() // 1 byte
}

/** Typed overload: encode from a [PduType] enum (resolves to its 3-bit wire ordinal). */
internal fun encodeAdPduHeader(version: Int, pduType: PduType, reserved: Int): ByteArray =
    encodeAdPduHeader(version, pduType.wire, reserved)
